name: chat-finished-mark
status: approved
approvato: 2026-09-29 12:45
risposta: "Comunque, quando c'è un topic, qualcosa che ha finito, esattamente come un terminale che ha finito, dovrei vederlo anche su Topics e saltare le notifiche. Al momento non le vedo sul mio Topics in locale."
