import { launch, CDP, newPage, sleep } from "./bench.mjs";
import { writeFileSync } from "node:fs";
const eng=process.argv[2], port=+process.argv[3];
const b=await launch(eng,port); const br=await CDP.connect(b.wsUrl); const {sessionId:s}=await newPage(br);
await br.send("Emulation.setDeviceMetricsOverride",{width:700,height:380,deviceScaleFactor:1,mobile:false},s).catch(()=>{});
await br.send("Page.navigate",{url:"http://127.0.0.1:4701/"},s); await sleep(2500);
const p=await br.send("Runtime.evaluate",{expression:"JSON.stringify(window.__probe)",returnByValue:true},s);
console.log(eng, "getImageData ->", p.result?.value);
const sc=await br.send("Page.captureScreenshot",{format:"png"},s);
writeFileSync(`vs/canvas-${eng}.png`,Buffer.from(sc.data,"base64"));
br.close();b.dispose();process.exit(0);
