import { launch, CDP, newPage, sleep } from "./bench.mjs";
const b=await launch("headless-shell",9732); const br=await CDP.connect(b.wsUrl); const {sessionId:s}=await newPage(br);
await br.send("Emulation.setDeviceMetricsOverride",{width:1440,height:900,deviceScaleFactor:2,mobile:false},s);
await br.send("Page.navigate",{url:"http://127.0.0.1:4800/"},s); await sleep(5000);
let f=0,bytes=0; br.on("Page.screencastFrame",(q)=>{f++;bytes+=q.data.length*0.75;br.send("Page.screencastFrameAck",{sessionId:q.sessionId},s).catch(()=>{})});
await br.send("Page.startScreencast",{format:"jpeg",quality:80,everyNthFrame:1,maxWidth:1440,maxHeight:900},s);
await br.send("Runtime.evaluate",{expression:"(()=>{const d=document.createElement('div');d.style.cssText='position:fixed;top:0;left:0;width:200px;height:60px;background:#f00';document.body.appendChild(d);let i=0;setInterval(()=>{d.style.transform=`translateX(${(i=(i+7)%400)}px)`},16)})()"},s);
await sleep(5000); await br.send("Page.stopScreencast",{},s).catch(()=>{});
console.log(`chrome, stessa UI: ${(f/5).toFixed(1)} fps, ${(bytes/5/1024/1024).toFixed(2)} MB/s`);
br.close();b.dispose();process.exit(0);
