/**
 * The proof numbers on the home page, read from the repository at build time.
 *
 * Stars (0) and downloads (54) are the wrong proof for a project this young and
 * putting them on the page would be an own goal. What is true and checkable is
 * the rate of work: commits, how many landed this week, and which version is on
 * the release page. Anyone can verify all of it against the public repo, which
 * is the only kind of number worth printing.
 *
 * NOTHING IN HERE IS TYPED BY HAND, and that is the whole point of the file.
 * It used to carry a FALLBACK literal for builds without git history: 2,680
 * commits, 78 releases, version 2.2.11, with a comment calling it stale-safe. A
 * constant of that shape does not degrade, it lies. The hero was still printing
 * v2.2.11 at 2.2.133, a hundred and twenty releases later, and nothing broke
 * because a hard-coded number cannot fail. So: a count git cannot answer is
 * `null` and the page prints one line fewer, and the version comes from the
 * file the release pipeline bumps.
 *
 * `releases` is gone rather than fixed. No file in the tree carries a truthful
 * count of published releases, local tags lag whatever CI published, and the
 * changelog data is regenerated by hand, so every candidate was another number
 * that could be wrong without anyone noticing.
 */
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
// Resolved by the bundler, not at run time, and that distinction is the whole
// reason it is an import. Astro emits this module into
// `landing/dist/.prerender/chunks/`, so any path built from `import.meta.url`
// points at `landing/` there and at the repo root when `scripts/og-image.mjs`
// runs the same file from source. A `readFileSync` of the Tauri config was
// therefore correct for og-image and ENOENT for `astro build`, which died
// rendering /v3. An import is evaluated once, at build time, in both callers.
import tauriConf from '../../../desktop-tauri/src-tauri/tauri.conf.json';

/**
 * The repository root: three levels above `landing/src/lib` when this module
 * runs from source. Only `git` uses it, and git searches upward for the
 * enclosing repository, so the bundled copy resolving one level short is
 * harmless here (it is not, for a file read: see the import above).
 */
const ROOT = fileURLToPath(new URL('../../..', import.meta.url));

export interface RepoStats {
  /** Total commits, or null when this checkout has no usable history. */
  commits: number | null;
  /** Commits in the last seven days, or null. */
  commitsLast7: number | null;
  /** ISO date of the first commit, or null. */
  since: string | null;
  /** The version this tree ships. Never null: the file it comes from is committed. */
  version: string;
  /**
   * Whether the git numbers above are real. Derived from them rather than set,
   * so it cannot disagree with them. `scripts/og-image.mjs` reads it to label
   * the card it renders.
   */
  live: boolean;
}

/**
 * The version, taken from the file the release bumps.
 *
 * `desktop-tauri/src-tauri/tauri.conf.json` is what Tauri stamps into every
 * installer name and into `latest.json`, and `auto-bump.yml` moves it in
 * lockstep with the root package.json on every merge to main. Reading it is the
 * only way this page can name a version without a person remembering to retype
 * one.
 *
 * A missing or shapeless file throws instead of defaulting, on the same grounds
 * as changelog.ts: a build that stops costs less than a page that invents.
 */
function shippedVersion(): string {
  const version = (tauriConf as { version?: unknown }).version;
  if (typeof version !== 'string' || !/^\d+\.\d+\.\d+/.test(version)) {
    throw new Error('desktop-tauri/src-tauri/tauri.conf.json: no usable "version". Has the Tauri config changed shape?');
  }
  return version;
}

function git(args: string[]): string {
  return execFileSync('git', args, {
    cwd: ROOT,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  }).trim();
}

let cached: RepoStats | null = null;

export function repoStats(): RepoStats {
  if (cached) return cached;
  let history: Pick<RepoStats, 'commits' | 'commitsLast7' | 'since'> = {
    commits: null,
    commitsLast7: null,
    since: null,
  };
  try {
    const commits = Number(git(['rev-list', '--count', 'HEAD']));
    const commitsLast7 = Number(git(['rev-list', '--count', '--since=7 days ago', 'HEAD']));
    const since = git(['log', '--reverse', '--format=%as', '--max-parents=0']).split('\n')[0];
    // A shallow clone answers all three without erroring and answers them
    // wrong: its grafted commit has no parents, so it passes for a root. The
    // numbers are only kept when they look like a full history.
    if (Number.isFinite(commits) && commits >= 100 && /^\d{4}-\d{2}-\d{2}$/.test(since)) {
      history = {
        commits,
        commitsLast7: Number.isFinite(commitsLast7) ? commitsLast7 : null,
        since,
      };
    }
  } catch {
    // Left null on purpose. No history is a reason to print less, never a
    // reason to print a guess.
  }
  cached = { ...history, version: shippedVersion(), live: history.commits !== null };
  return cached;
}

/** "11 February 2026", the format the rest of the site dates things in. */
export function longDate(iso: string): string {
  return new Date(`${iso}T12:00:00Z`).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  });
}
