name: notifications-one-truth
status: approved
approvato: 2026-09-29 15:27
risposta: "vedo 133 notifiche, aprendo le notifiche della sidebar se ne vanno ma restano ovunque, ma in realtà dovrebbero essere sincronizzate con le vere notifiche."
