schema: spec-driven
created: 2026-10-04
name: cloud-nodes
status: draft
parcheggiata: "piano futuro, richiesta del 04/10"
richiesta: "vabèlasciamo stare per ora , poi valutiamo qualcosa di top di scalabile, in realtà iniziamolo a fare e lo teniamo la come futuro piano cloud per avere le cose pesanti la?"
