name: split-dnd-all-directions
status: approved
approvato: 2026-09-22
risposta: "card f067c822-447b-4fff-bace-5a1b4aa1d071 (e' da rivedere bene il sistema di dnd e split completo in tutte le direzioni siccome al momento non mi fa fare split bene ovunque all'interno del progetto. approfittane per assicurarti che sia perfetto)"
