#!/usr/bin/env bash
# Set the app version in LOCKSTEP across the four places it is written:
#   - package.json                              ("version")
#   - desktop-tauri/src-tauri/tauri.conf.json   ("version")
#   - desktop-tauri/src-tauri/Cargo.toml        (the [package] version line)
#   - desktop-tauri/src-tauri/Cargo.lock        (the [[package]] "app" stanza)
#
# THE FOURTH IS THE ONE THAT GETS FORGOTTEN, and not by distraction: the first
# three are configuration files you open on purpose, the lock is generated by
# cargo and nobody edits it by hand. Twice in one night a bump touched three of
# four; both times `tests/unit/version-lockstep.test.ts` caught it and both times
# it was fixed by hand before landing. So this script is the gesture, and the
# gesture has a name: `bun run bump` (package.json), which is what CONTRIBUTING
# and the board kickoff point at. Open the files by hand and you are back to
# remembering four things.
#
# Surgical text replacement (not a JSON re-serialize), so only the version
# string changes and every file keeps its exact formatting → minimal diff.
#
# Usage: scripts/bump-version.sh [patch|minor|major|X.Y.Z|sync]   (default: patch)
#   patch|minor|major  increment package.json's version, write all four
#   X.Y.Z              set all four to exactly this version
#   sync               write package.json's CURRENT version into the other three
#                      (the repair gesture: realigns a tree that already drifted,
#                       without inventing a new version number)
#
# Prints the resulting version to stdout (nothing else on stdout) so callers can
# capture it: NEW=$(scripts/bump-version.sh patch)
#
# BUMP_ROOT overrides the repo root — the only reason it exists is that
# `tests/unit/bump-version.test.ts` runs the real script against a throwaway
# copy of the four files instead of against the checkout it lives in.
set -euo pipefail
REPO_ROOT="${BUMP_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$REPO_ROOT"
PART="${1:-patch}"

python3 - "$PART" <<'PY'
import re, sys

arg = sys.argv[1]

PKG = "package.json"
TAURI = "desktop-tauri/src-tauri/tauri.conf.json"
CARGO = "desktop-tauri/src-tauri/Cargo.toml"
LOCK = "desktop-tauri/src-tauri/Cargo.lock"

# Read the current version from package.json (the canonical source).
cur = re.search(r'"version"\s*:\s*"(\d+)\.(\d+)\.(\d+)"', open(PKG).read())
if not cur:
    sys.exit("bump-version: no semver \"version\" in package.json")
x, y, z = (int(n) for n in cur.groups())

if arg == "major":   new = f"{x + 1}.0.0"
elif arg == "minor": new = f"{x}.{y + 1}.0"
elif arg == "patch": new = f"{x}.{y}.{z + 1}"
elif arg == "sync":  new = f"{x}.{y}.{z}"
elif re.fullmatch(r"\d+\.\d+\.\d+", arg): new = arg
else:
    sys.exit(f"bump-version: unknown argument '{arg}' (use patch|minor|major|X.Y.Z|sync)")

def sub_once(path, pattern, repl):
    s = open(path).read()
    s2, n = re.subn(pattern, repl, s, count=1)
    if n != 1:
        sys.exit(f"bump-version: version line not found in {path}")
    open(path, "w").write(s2)

# JSON: "version": "X.Y.Z"  (first occurrence = the top-level app version)
sub_once(PKG,   r'("version"\s*:\s*")\d+\.\d+\.\d+(")', rf'\g<1>{new}\g<2>')
sub_once(TAURI, r'("version"\s*:\s*")\d+\.\d+\.\d+(")', rf'\g<1>{new}\g<2>')
# Cargo.toml: a line-anchored `version = "X.Y.Z"` = the [package] version
# (dependency versions are inline `name = { version = "…" }`, never line-start).
sub_once(CARGO, r'(?m)^(version\s*=\s*")\d+\.\d+\.\d+(")', rf'\g<1>{new}\g<2>')
# Cargo.lock: keep the "app" package stanza in lockstep too. Without this
# every bump leaves the lock one version behind, and the NEXT local
# `cargo build`/`cargo check` rewrites it as uncommitted noise (a dirty
# Cargo.lock rode along in two PRs before this).
sub_once(LOCK, r'(?m)^(name = "app"\nversion = ")\d+\.\d+\.\d+(")', rf'\g<1>{new}\g<2>')

print(new)
PY
