#!/usr/bin/env bun
// Regenerate server/db/migrations-embedded.ts — a manifest that carries the TEXT
// of every server/db/migrations/*.sql as a string literal.
//
// WHY: the release ships the server as a `bun build --compile` single binary
// (the Tauri sidecar). In a compiled binary `import.meta.dir` is a virtual path
// (`/$bunfs/root`) and `readdirSync`/`readFileSync` over the migrations dir find
// NOTHING on disk, so the DB would boot with no tables. This manifest is the
// embedded fallback `runMigrations` uses when the on-disk migrations dir is
// absent; dev / launchd runs still read from disk and never load it.
//
// WHY STRING LITERALS AND NOT `import x from "./m.sql" with { type: "text" }`.
// The manifest is loaded by a lazy `require` (server/db.ts, `resolveMigrations`),
// so that the migrations stay out of the boot graph when the folder exists.
// Through `require`, Bun 1.3.8 (the production server's runtime) ignores the
// import attribute and hands back the FILE PATH of each `.sql` instead of its
// text; worse, the module cache then holds those paths, so a later static import
// of the manifest in the same process gets paths too (order-dependent reds in the
// 1.3.8 unit suite, cloud-quality-pass V3 D1). A string literal is a string on
// every Bun, through `require`, `import` and `--compile` alike: there is no
// loader left to get wrong. Measured with server/db/embedded-fallback-fresh-process.test.ts.
//
// The price: the SQL lives twice in the repo, and EDITING a migration (not only
// adding one) now needs a regeneration. Both are guarded: the drift gate
// (server/db/migrations-embedded.test.ts) compares every entry to the file byte
// for byte, and CI reruns this script and fails on a stale manifest.
//
// Run this whenever you ADD, RENAME or EDIT a migration:
//   bun run scripts/gen-migrations-manifest.ts
// (`bun run migration:new <slug>` runs it by itself.)
//
// ONE LINE PER MIGRATION, on purpose: two cards in parallel each add their own
// migration, and this file is the one place both must touch. `.gitattributes`
// marks it `merge=union`, so git keeps both added lines and the merge goes
// through. The ORDER of the array after such a merge may not be ascending, and
// that is fine: `resolveMigrations` in server/db.ts always sorts by (number,
// name) before applying.

import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const repoRoot = join(import.meta.dir, "..");
const migrationsDir = join(repoRoot, "server", "db", "migrations");
const outFile = join(repoRoot, "server", "db", "migrations-embedded.ts");

const versionOf = (f: string) => parseInt(f.match(/^(\d+)-/)![1], 10);

const files = readdirSync(migrationsDir)
  .filter((f) => /^\d+-.+\.sql$/.test(f))
  // Numero, poi nome: lo stesso ordine del runner. Il numero da solo non basta
  // più — due migration scritte nello stesso secondo lo condividono.
  .sort((a, b) => versionOf(a) - versionOf(b) || (a < b ? -1 : a > b ? 1 : 0));

if (files.length === 0) {
  console.error(`[gen-migrations] no migration .sql files found in ${migrationsDir}`);
  process.exit(1);
}

const entries = files.map((file) => {
  const sql = readFileSync(join(migrationsDir, file), "utf-8");
  return `  { version: ${versionOf(file)}, name: ${JSON.stringify(file)}, sql: ${JSON.stringify(sql)} },`;
});

const banner = `// AUTO-GENERATED by scripts/gen-migrations-manifest.ts — DO NOT EDIT BY HAND.
// Regenerate after adding/renaming/editing a migration:  bun run scripts/gen-migrations-manifest.ts
//
// Embeds the text of every server/db/migrations/*.sql, one line each, so the \`bun build --compile\`
// server sidecar can run migrations without the on-disk dir (see the script header
// and server/db.ts runMigrations for the disk-vs-embedded fallback).
`;

const body = `${banner}
export interface EmbeddedMigration {
  version: number;
  name: string;
  sql: string;
}

/** All migrations in ascending version order, embedded at build time. */
export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [
${entries.join("\n")}
];
`;

writeFileSync(outFile, body);
console.log(`[gen-migrations] wrote ${outFile} with ${files.length} migration(s)`);
