#!/usr/bin/env bun
// Regenerate server/db/migrations-embedded.ts — a manifest that STATIC-imports
// every server/db/migrations/*.sql as text (`with { type: "text" }`).
//
// WHY: the release ships the server as a `bun build --compile` single binary
// (the Tauri sidecar). In a compiled binary `import.meta.dir` is a virtual path
// (`/$bunfs/root`) and `readdirSync`/`readFileSync` over the migrations dir find
// NOTHING on disk, so the DB would boot with no tables. Static text imports, by
// contrast, are embedded into the binary and survive `--compile` (verified). This
// manifest is the embedded fallback `runMigrations` uses when the on-disk
// migrations dir is absent; dev / launchd runs still read from disk and ignore it.
//
// Run this whenever you ADD or RENAME a migration:
//   bun run scripts/gen-migrations-manifest.ts
// (`bun run migration:new <slug>` lo lancia da sé; CI lo rilancia e fallisce se
// il manifest è vecchio — vedi CONTRIBUTING.)
//
// PERCHÉ GLI IDENTIFICATORI VENGONO DAL NOME e non dalla posizione: due card in
// parallelo aggiungono ciascuna la propria migration, e questo file è l'unico
// posto che TUTTE e due devono toccare. Con `m000, m001, …` per indice, le due
// aggiunte si contendono lo stesso identificatore e il merge è un conflitto da
// risolvere a mano — la stessa contesa che il prefisso timestamp toglie ai nomi
// dei file (scripts/new-migration.ts). Con l'identificatore derivato dal nome le
// due righe sono diverse, e `.gitattributes` marca questo file `merge=union`:
// git tiene entrambe le aggiunte e il merge passa liscio. L'ORDINE dell'array
// dopo un merge del genere può non essere crescente, e va bene: `resolveMigrations`
// in server/db.ts riordina sempre per (numero, nome) prima di applicare.

import { readdirSync, writeFileSync } from "fs";
import { join } from "path";

const repoRoot = join(import.meta.dir, "..");
const migrationsDir = join(repoRoot, "server", "db", "migrations");
const outFile = join(repoRoot, "server", "db", "migrations-embedded.ts");

const versionOf = (f: string) => parseInt(f.match(/^(\d+)-/)![1], 10);

const files = readdirSync(migrationsDir)
  .filter((f) => /^\d+-.+\.sql$/.test(f))
  // Numero, poi nome: lo stesso ordine del runner. Il numero da solo non basta
  // più — due migration scritte nello stesso secondo lo condividono.
  .sort((a, b) => versionOf(a) - versionOf(b) || (a < b ? -1 : a > b ? 1 : 0));

if (files.length === 0) {
  console.error(`[gen-migrations] no migration .sql files found in ${migrationsDir}`);
  process.exit(1);
}

/** `089-retirements.sql` → `m089_retirements`. Dal NOME, mai dalla posizione. */
const identOf = (file: string) => `m${file.replace(/\.sql$/, "").replace(/[^A-Za-z0-9]/g, "_")}`;

const imports: string[] = [];
const entries: string[] = [];
const visti = new Map<string, string>();
for (const file of files) {
  const ident = identOf(file);
  const gemello = visti.get(ident);
  if (gemello) {
    // Non può succedere finché i nomi sono `<numero>-<slug-in-kebab>.sql`, ma se
    // succedesse il file generato non compilerebbe: meglio dirlo qui.
    console.error(`[gen-migrations] ${file} e ${gemello} danno lo stesso identificatore (${ident})`);
    process.exit(1);
  }
  visti.set(ident, file);
  imports.push(`import ${ident} from "./migrations/${file}" with { type: "text" };`);
  entries.push(`  { version: ${versionOf(file)}, name: ${JSON.stringify(file)}, sql: ${ident} },`);
}

const banner = `// AUTO-GENERATED by scripts/gen-migrations-manifest.ts — DO NOT EDIT BY HAND.
// Regenerate after adding/renaming a migration:  bun run scripts/gen-migrations-manifest.ts
//
// Embeds every server/db/migrations/*.sql as text so the \`bun build --compile\`
// server sidecar can run migrations without the on-disk dir (see the script header
// and server/db.ts runMigrations for the disk-vs-embedded fallback).
`;

const body = `${banner}
${imports.join("\n")}

export interface EmbeddedMigration {
  version: number;
  name: string;
  sql: string;
}

/** All migrations in ascending version order, embedded at build time. */
export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [
${entries.join("\n")}
];
`;

writeFileSync(outFile, body);
console.log(`[gen-migrations] wrote ${outFile} with ${files.length} migration(s)`);
