#!/usr/bin/env bun
// Regenerate server/db/migrations-embedded.ts — a manifest that STATIC-imports
// every server/db/migrations/*.sql as text (`with { type: "text" }`).
//
// WHY: the release ships the server as a `bun build --compile` single binary
// (the Tauri sidecar). In a compiled binary `import.meta.dir` is a virtual path
// (`/$bunfs/root`) and `readdirSync`/`readFileSync` over the migrations dir find
// NOTHING on disk, so the DB would boot with no tables. Static text imports, by
// contrast, are embedded into the binary and survive `--compile` (verified). This
// manifest is the embedded fallback `runMigrations` uses when the on-disk
// migrations dir is absent; dev / launchd runs still read from disk and ignore it.
//
// Run this whenever you ADD or RENAME a migration:
//   bun run scripts/gen-migrations-manifest.ts
// (CI also runs it and fails if the manifest is stale — see CONTRIBUTING.)

import { readdirSync, writeFileSync } from "fs";
import { join } from "path";

const repoRoot = join(import.meta.dir, "..");
const migrationsDir = join(repoRoot, "server", "db", "migrations");
const outFile = join(repoRoot, "server", "db", "migrations-embedded.ts");

const files = readdirSync(migrationsDir)
  .filter((f) => /^\d+-.+\.sql$/.test(f))
  .sort();

if (files.length === 0) {
  console.error(`[gen-migrations] no migration .sql files found in ${migrationsDir}`);
  process.exit(1);
}

const imports: string[] = [];
const entries: string[] = [];
files.forEach((file, i) => {
  const ident = `m${String(i).padStart(3, "0")}`;
  const m = file.match(/^(\d+)-(.+)\.sql$/)!;
  const version = parseInt(m[1], 10);
  imports.push(`import ${ident} from "./migrations/${file}" with { type: "text" };`);
  entries.push(`  { version: ${version}, name: ${JSON.stringify(file)}, sql: ${ident} },`);
});

const banner = `// AUTO-GENERATED by scripts/gen-migrations-manifest.ts — DO NOT EDIT BY HAND.
// Regenerate after adding/renaming a migration:  bun run scripts/gen-migrations-manifest.ts
//
// Embeds every server/db/migrations/*.sql as text so the \`bun build --compile\`
// server sidecar can run migrations without the on-disk dir (see the script header
// and server/db.ts runMigrations for the disk-vs-embedded fallback).
`;

const body = `${banner}
${imports.join("\n")}

export interface EmbeddedMigration {
  version: number;
  name: string;
  sql: string;
}

/** All migrations in ascending version order, embedded at build time. */
export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [
${entries.join("\n")}
];
`;

writeFileSync(outFile, body);
console.log(`[gen-migrations] wrote ${outFile} with ${files.length} migration(s)`);
