/**
 * ChangelogModal — the in-app "Novità" surface, opened from the version chip's
 * popover (VersionPopover → SidebarStatusBar). Shows the per-version changelog,
 * navigable by version, with the running build highlighted. Data is fetched lazily
 * from the static `/changelog.json` (generated by `bun run changelog`, served from
 * public/) so the 350KB+ history never bloats the JS bundle. Renders the Italian
 * (`it`) copy — the public English rendering lives on the landing site.
 */
import { useEffect, useMemo, useRef, useState } from 'react';
import { useT } from '@/hooks/useT';
import { createPortal } from 'react-dom';
import { Sparkles, X, Wrench, Zap, Cog, ChevronRight } from 'lucide-react';
import { MODAL_OVERLAY, MODAL_PANEL } from '@/lib/modalStyles';
import { useModalDialog } from '@/hooks/useModalDialog';

interface Entry {
  it: string;
  en: string;
  scope: string | null;
  breaking?: boolean;
}
interface Version {
  version: string;
  date: string;
  sections: { new: Entry[]; fixes: Entry[]; perf: Entry[]; internal: Entry[] };
}

const SECTIONS: { key: keyof Version['sections']; label: string; Icon: typeof Sparkles }[] = [
  { key: 'new', label: 'Novità', Icon: Sparkles },
  { key: 'fixes', label: 'Correzioni', Icon: Wrench },
  { key: 'perf', label: 'Prestazioni', Icon: Zap },
];

export function ChangelogModal({
  currentVersion,
  onClose,
}: {
  currentVersion: string;
  onClose: () => void;
}) {
  const tr = useT();
  const [data, setData] = useState<Version[] | null>(null);
  const [error, setError] = useState(false);
  const [selected, setSelected] = useState<string | null>(null);
  const [showInternal, setShowInternal] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  // Escape chiude, il Tab resta dentro, il focus torna da dove è partito:
  // il contratto comune dei dialoghi (hooks/useModalDialog). Prima l'Escape era
  // scritto a mano qui e in bolla, quindi con due dialoghi aperti rispondevano
  // entrambi.
  const panelRef = useRef<HTMLDivElement>(null);
  useModalDialog({ onClose, panelRef });

  // Lazy-load the generated changelog.
  useEffect(() => {
    let alive = true;
    fetch('/changelog.json', { cache: 'no-cache' })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then((json: Version[]) => {
        if (!alive) return;
        setData(json);
        // Default to the running version if present, else the newest.
        const match = json.find((v) => v.version === currentVersion);
        setSelected(match ? match.version : json[0]?.version ?? null);
      })
      .catch(() => alive && setError(true));
    return () => { alive = false; };
  }, [currentVersion]);

  const active = useMemo(() => data?.find((v) => v.version === selected) ?? null, [data, selected]);

  // Scroll the content back to top on version change (DOM side-effect). The
  // internal-toggle is reset in the rail click handler, not here, to avoid a
  // setState-in-effect cascade.
  useEffect(() => {
    if (contentRef.current) contentRef.current.scrollTop = 0;
  }, [selected]);

  return createPortal(
    <div className={MODAL_OVERLAY} onClick={onClose}>
      <div
        ref={panelRef}
        role="dialog"
        aria-modal="true"
        aria-label={tr('changelog.title')}
        data-testid="changelog-modal"
        className={`${MODAL_PANEL} w-[min(880px,94vw)] h-[min(640px,86vh)] flex flex-col`}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center gap-2 px-4 h-12 shrink-0 border-b border-app-border">
          <Sparkles size={15} className="text-primary" />
          <span className="text-[13px] font-semibold text-app-text">{tr('changelog.title')}</span>
          <span className="text-[11px] text-app-text-muted">{tr('changelog.subtitle')}</span>
          <button
            onClick={onClose}
            className="ml-auto p-1 rounded hover:bg-app-hover text-app-text-muted hover:text-app-text transition-colors"
            aria-label={tr('common.close')}
          >
            <X size={15} />
          </button>
        </div>

        {error && (
          <div className="flex-1 grid place-items-center text-[12px] text-app-text-muted">
            {tr('changelog.unavailable')}
          </div>
        )}

        {!error && !data && (
          <div className="flex-1 grid place-items-center text-[12px] text-app-text-muted">Carico…</div>
        )}

        {!error && data && (
          <div className="flex-1 min-h-0 flex">
            {/* Version rail */}
            <nav className="w-40 shrink-0 border-r border-app-border overflow-y-auto py-1">
              {data.map((v) => {
                const isSel = v.version === selected;
                const isCurrent = v.version === currentVersion;
                return (
                  <button
                    key={v.version}
                    data-testid={`changelog-version-${v.version}`}
                    onClick={() => { setSelected(v.version); setShowInternal(false); }}
                    className={`w-full text-left px-3 py-1.5 flex items-center gap-1.5 transition-colors ${
                      isSel ? 'bg-primary/10 text-app-text' : 'text-app-text-secondary hover:bg-app-hover'
                    }`}
                  >
                    <span className="text-[12px] tabular-nums font-medium">v{v.version}</span>
                    {isCurrent && (
                      <span className="px-1 rounded bg-emerald-500/15 text-emerald-500 text-[8px] font-semibold leading-tight">
                        in uso
                      </span>
                    )}
                    <span className="ml-auto text-[9px] text-app-text-muted tabular-nums">{v.date}</span>
                  </button>
                );
              })}
            </nav>

            {/* Selected version content */}
            <div ref={contentRef} className="flex-1 min-w-0 overflow-y-auto px-5 py-4">
              {active && (
                <>
                  <div className="flex items-baseline gap-2 mb-3">
                    <h2 className="text-[15px] font-semibold text-app-text tabular-nums">v{active.version}</h2>
                    {active.version === currentVersion && (
                      <span className="px-1.5 py-0.5 rounded bg-emerald-500/15 text-emerald-500 text-[9px] font-semibold">
                        versione in uso
                      </span>
                    )}
                    {active.date && <span className="text-[11px] text-app-text-muted ml-auto">{active.date}</span>}
                  </div>

                  {SECTIONS.map(({ key, label, Icon }) => {
                    const items = active.sections[key];
                    if (!items.length) return null;
                    return (
                      <section key={key} className="mb-4">
                        <div className="flex items-center gap-1.5 mb-1.5">
                          <Icon size={12} className="text-app-text-muted" />
                          <h3 className="text-[10px] uppercase tracking-wide text-app-text-muted font-semibold">{label}</h3>
                        </div>
                        <ul className="space-y-1">
                          {items.map((e, i) => (
                            <li key={i} className="text-[12px] text-app-text-secondary leading-relaxed flex gap-1.5">
                              <span className="text-app-text-muted mt-[3px]">•</span>
                              <span>
                                {e.scope && <span className="font-medium text-app-text">{e.scope}</span>}
                                {e.scope && ' · '}
                                {e.it}
                                {e.breaking && (
                                  <span className="ml-1.5 px-1 rounded bg-amber-500/15 text-amber-500 text-[8px] font-semibold uppercase">
                                    breaking
                                  </span>
                                )}
                              </span>
                            </li>
                          ))}
                        </ul>
                      </section>
                    );
                  })}

                  {/* Under the hood — collapsed by default */}
                  {active.sections.internal.length > 0 && (
                    <div className="mt-2 border-t border-app-border pt-2">
                      <button
                        onClick={() => setShowInternal((s) => !s)}
                        className="flex items-center gap-1 text-[10px] uppercase tracking-wide text-app-text-muted hover:text-app-text-secondary transition-colors"
                      >
                        <ChevronRight size={11} className={`transition-transform ${showInternal ? 'rotate-90' : ''}`} />
                        <Cog size={11} />
                        {tr('changelog.internal', { n: active.sections.internal.length })}
                      </button>
                      {showInternal && (
                        <ul className="space-y-1 mt-1.5">
                          {active.sections.internal.map((e, i) => (
                            <li key={i} className="text-[11px] text-app-text-muted leading-relaxed flex gap-1.5">
                              <span className="mt-[3px]">•</span>
                              <span>
                                {e.scope && <span className="font-medium text-app-text-secondary">{e.scope}</span>}
                                {e.scope && ' · '}
                                {e.it}
                              </span>
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  )}
                </>
              )}
            </div>
          </div>
        )}

        {/* Footer — link to the full public changelog */}
        <div className="h-9 shrink-0 border-t border-app-border flex items-center px-4">
          <a
            href="https://topics.armonia.io/changelog.html"
            target="_blank"
            rel="noopener"
            className="text-[11px] text-app-text-muted hover:text-primary transition-colors"
          >
            {tr('changelog.full')}
          </a>
        </div>
      </div>
    </div>,
    document.body,
  );
}
