// AUTO-GENERATED by scripts/gen-migrations-manifest.ts — DO NOT EDIT BY HAND.
// Regenerate after adding/renaming a migration:  bun run scripts/gen-migrations-manifest.ts
//
// Embeds every server/db/migrations/*.sql as text so the `bun build --compile`
// server sidecar can run migrations without the on-disk dir (see the script header
// and server/db.ts runMigrations for the disk-vs-embedded fallback).

import m000 from "./migrations/001-initial.sql" with { type: "text" };
import m001 from "./migrations/002-agent-autonomy.sql" with { type: "text" };
import m002 from "./migrations/003-task-archived.sql" with { type: "text" };
import m003 from "./migrations/004-drop-disabled-templates.sql" with { type: "text" };
import m004 from "./migrations/005-message-branching.sql" with { type: "text" };
import m005 from "./migrations/006-push-subscriptions.sql" with { type: "text" };
import m006 from "./migrations/007-ui-state.sql" with { type: "text" };
import m007 from "./migrations/008-terminal-sessions.sql" with { type: "text" };
import m008 from "./migrations/009-terminal-claude-session-id.sql" with { type: "text" };
import m009 from "./migrations/010-topic-provider.sql" with { type: "text" };
import m010 from "./migrations/011-terminal-session-status.sql" with { type: "text" };
import m011 from "./migrations/012-ui-state-payload-version.sql" with { type: "text" };
import m012 from "./migrations/013-topic-model.sql" with { type: "text" };
import m013 from "./migrations/014-message-meta.sql" with { type: "text" };
import m014 from "./migrations/015-message-blocks.sql" with { type: "text" };
import m015 from "./migrations/016-projects.sql" with { type: "text" };
import m016 from "./migrations/017-worktrees.sql" with { type: "text" };
import m017 from "./migrations/018-topics-worktree-id.sql" with { type: "text" };
import m018 from "./migrations/019-topic-initial-message.sql" with { type: "text" };
import m019 from "./migrations/020-machines.sql" with { type: "text" };
import m020 from "./migrations/021-topics-machine-id.sql" with { type: "text" };
import m021 from "./migrations/022-claude-code-sessions.sql" with { type: "text" };
import m022 from "./migrations/023-claude-code-sessions-fk.sql" with { type: "text" };
import m023 from "./migrations/024-topic-fast-mode.sql" with { type: "text" };
import m024 from "./migrations/025-agent-epochs.sql" with { type: "text" };
import m025 from "./migrations/026-master-topic-mode.sql" with { type: "text" };
import m026 from "./migrations/027-claude-session-tracker.sql" with { type: "text" };
import m027 from "./migrations/028-terminal-parent-session-key.sql" with { type: "text" };
import m028 from "./migrations/029-terminal-session-type-check.sql" with { type: "text" };
import m029 from "./migrations/030-terminal-session-name-source.sql" with { type: "text" };
import m030 from "./migrations/031-task-dispatch.sql" with { type: "text" };
import m031 from "./migrations/032-terminal-sessions-status-index.sql" with { type: "text" };
import m032 from "./migrations/033-topic-effort.sql" with { type: "text" };
import m033 from "./migrations/034-task-parent.sql" with { type: "text" };
import m034 from "./migrations/035-task-output-url.sql" with { type: "text" };
import m035 from "./migrations/036-task-plan-first.sql" with { type: "text" };
import m036 from "./migrations/037-task-comment-media.sql" with { type: "text" };
import m037 from "./migrations/038-global-dispatch.sql" with { type: "text" };
import m038 from "./migrations/039-task-comment-kind.sql" with { type: "text" };
import m039 from "./migrations/040-task-agent-usage.sql" with { type: "text" };
import m040 from "./migrations/041-task-model.sql" with { type: "text" };
import m041 from "./migrations/042-task-blocked-by.sql" with { type: "text" };
import m042 from "./migrations/043-task-priority-auto.sql" with { type: "text" };
import m043 from "./migrations/044-topic-standalone.sql" with { type: "text" };
import m044 from "./migrations/045-backfill-catchall-standalone.sql" with { type: "text" };
import m045 from "./migrations/046-standalone-husk-topics.sql" with { type: "text" };
import m046 from "./migrations/047-classify-parked-dispatch-state.sql" with { type: "text" };
import m047 from "./migrations/048-task-agent-cache-read.sql" with { type: "text" };
import m048 from "./migrations/049-topic-mcp-policy.sql" with { type: "text" };
import m049 from "./migrations/050-board-dispatch-retry.sql" with { type: "text" };
import m050 from "./migrations/051-board-dispatch-auto-merge.sql" with { type: "text" };
import m051 from "./migrations/052-board-dispatch-model.sql" with { type: "text" };
import m052 from "./migrations/053-board-max-agents-auto.sql" with { type: "text" };
import m053 from "./migrations/054-app-settings.sql" with { type: "text" };
import m054 from "./migrations/055-task-preview-image.sql" with { type: "text" };
import m055 from "./migrations/056-compaction-markers.sql" with { type: "text" };
import m056 from "./migrations/057-compaction-post-tokens-sanity.sql" with { type: "text" };
import m057 from "./migrations/058-task-dispatch-defer.sql" with { type: "text" };
import m058 from "./migrations/059-task-delivery-landing.sql" with { type: "text" };
import m059 from "./migrations/060-session-context.sql" with { type: "text" };
import m060 from "./migrations/061-review-checks.sql" with { type: "text" };
import m061 from "./migrations/062-delivered-by.sql" with { type: "text" };
import m062 from "./migrations/063-provider-sessions.sql" with { type: "text" };
import m063 from "./migrations/064-topic-goals.sql" with { type: "text" };
import m064 from "./migrations/065-task-fanout.sql" with { type: "text" };
import m065 from "./migrations/066-terminal-session-type-opencode.sql" with { type: "text" };
import m066 from "./migrations/067-drop-master-topic-leftovers.sql" with { type: "text" };
import m067 from "./migrations/068-close-stranded-approvals.sql" with { type: "text" };
import m068 from "./migrations/069-strip-slow-annotation.sql" with { type: "text" };
import m069 from "./migrations/070-message-cache-tokens.sql" with { type: "text" };
import m070 from "./migrations/071-drop-empty-assistant-turns.sql" with { type: "text" };
import m071 from "./migrations/072-sweep-dangling-message-refs.sql" with { type: "text" };
import m072 from "./migrations/073-topic-muted.sql" with { type: "text" };
import m073 from "./migrations/074-messages-timestamp-index.sql" with { type: "text" };
import m074 from "./migrations/075-topic-browser-state.sql" with { type: "text" };
import m075 from "./migrations/076-message-model.sql" with { type: "text" };
import m076 from "./migrations/077-fix-stale-opus-pricing.sql" with { type: "text" };
import m077 from "./migrations/078-topic-model-1m-window.sql" with { type: "text" };
import m078 from "./migrations/079-board-night-mode.sql" with { type: "text" };
import m079 from "./migrations/080-devices.sql" with { type: "text" };
import m080 from "./migrations/081-autonomy-default-acts.sql" with { type: "text" };
import m081 from "./migrations/082-task-shares.sql" with { type: "text" };
import m082 from "./migrations/083-grants.sql" with { type: "text" };

export interface EmbeddedMigration {
  version: number;
  name: string;
  sql: string;
}

/** All migrations in ascending version order, embedded at build time. */
export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [
  { version: 1, name: "001-initial.sql", sql: m000 },
  { version: 2, name: "002-agent-autonomy.sql", sql: m001 },
  { version: 3, name: "003-task-archived.sql", sql: m002 },
  { version: 4, name: "004-drop-disabled-templates.sql", sql: m003 },
  { version: 5, name: "005-message-branching.sql", sql: m004 },
  { version: 6, name: "006-push-subscriptions.sql", sql: m005 },
  { version: 7, name: "007-ui-state.sql", sql: m006 },
  { version: 8, name: "008-terminal-sessions.sql", sql: m007 },
  { version: 9, name: "009-terminal-claude-session-id.sql", sql: m008 },
  { version: 10, name: "010-topic-provider.sql", sql: m009 },
  { version: 11, name: "011-terminal-session-status.sql", sql: m010 },
  { version: 12, name: "012-ui-state-payload-version.sql", sql: m011 },
  { version: 13, name: "013-topic-model.sql", sql: m012 },
  { version: 14, name: "014-message-meta.sql", sql: m013 },
  { version: 15, name: "015-message-blocks.sql", sql: m014 },
  { version: 16, name: "016-projects.sql", sql: m015 },
  { version: 17, name: "017-worktrees.sql", sql: m016 },
  { version: 18, name: "018-topics-worktree-id.sql", sql: m017 },
  { version: 19, name: "019-topic-initial-message.sql", sql: m018 },
  { version: 20, name: "020-machines.sql", sql: m019 },
  { version: 21, name: "021-topics-machine-id.sql", sql: m020 },
  { version: 22, name: "022-claude-code-sessions.sql", sql: m021 },
  { version: 23, name: "023-claude-code-sessions-fk.sql", sql: m022 },
  { version: 24, name: "024-topic-fast-mode.sql", sql: m023 },
  { version: 25, name: "025-agent-epochs.sql", sql: m024 },
  { version: 26, name: "026-master-topic-mode.sql", sql: m025 },
  { version: 27, name: "027-claude-session-tracker.sql", sql: m026 },
  { version: 28, name: "028-terminal-parent-session-key.sql", sql: m027 },
  { version: 29, name: "029-terminal-session-type-check.sql", sql: m028 },
  { version: 30, name: "030-terminal-session-name-source.sql", sql: m029 },
  { version: 31, name: "031-task-dispatch.sql", sql: m030 },
  { version: 32, name: "032-terminal-sessions-status-index.sql", sql: m031 },
  { version: 33, name: "033-topic-effort.sql", sql: m032 },
  { version: 34, name: "034-task-parent.sql", sql: m033 },
  { version: 35, name: "035-task-output-url.sql", sql: m034 },
  { version: 36, name: "036-task-plan-first.sql", sql: m035 },
  { version: 37, name: "037-task-comment-media.sql", sql: m036 },
  { version: 38, name: "038-global-dispatch.sql", sql: m037 },
  { version: 39, name: "039-task-comment-kind.sql", sql: m038 },
  { version: 40, name: "040-task-agent-usage.sql", sql: m039 },
  { version: 41, name: "041-task-model.sql", sql: m040 },
  { version: 42, name: "042-task-blocked-by.sql", sql: m041 },
  { version: 43, name: "043-task-priority-auto.sql", sql: m042 },
  { version: 44, name: "044-topic-standalone.sql", sql: m043 },
  { version: 45, name: "045-backfill-catchall-standalone.sql", sql: m044 },
  { version: 46, name: "046-standalone-husk-topics.sql", sql: m045 },
  { version: 47, name: "047-classify-parked-dispatch-state.sql", sql: m046 },
  { version: 48, name: "048-task-agent-cache-read.sql", sql: m047 },
  { version: 49, name: "049-topic-mcp-policy.sql", sql: m048 },
  { version: 50, name: "050-board-dispatch-retry.sql", sql: m049 },
  { version: 51, name: "051-board-dispatch-auto-merge.sql", sql: m050 },
  { version: 52, name: "052-board-dispatch-model.sql", sql: m051 },
  { version: 53, name: "053-board-max-agents-auto.sql", sql: m052 },
  { version: 54, name: "054-app-settings.sql", sql: m053 },
  { version: 55, name: "055-task-preview-image.sql", sql: m054 },
  { version: 56, name: "056-compaction-markers.sql", sql: m055 },
  { version: 57, name: "057-compaction-post-tokens-sanity.sql", sql: m056 },
  { version: 58, name: "058-task-dispatch-defer.sql", sql: m057 },
  { version: 59, name: "059-task-delivery-landing.sql", sql: m058 },
  { version: 60, name: "060-session-context.sql", sql: m059 },
  { version: 61, name: "061-review-checks.sql", sql: m060 },
  { version: 62, name: "062-delivered-by.sql", sql: m061 },
  { version: 63, name: "063-provider-sessions.sql", sql: m062 },
  { version: 64, name: "064-topic-goals.sql", sql: m063 },
  { version: 65, name: "065-task-fanout.sql", sql: m064 },
  { version: 66, name: "066-terminal-session-type-opencode.sql", sql: m065 },
  { version: 67, name: "067-drop-master-topic-leftovers.sql", sql: m066 },
  { version: 68, name: "068-close-stranded-approvals.sql", sql: m067 },
  { version: 69, name: "069-strip-slow-annotation.sql", sql: m068 },
  { version: 70, name: "070-message-cache-tokens.sql", sql: m069 },
  { version: 71, name: "071-drop-empty-assistant-turns.sql", sql: m070 },
  { version: 72, name: "072-sweep-dangling-message-refs.sql", sql: m071 },
  { version: 73, name: "073-topic-muted.sql", sql: m072 },
  { version: 74, name: "074-messages-timestamp-index.sql", sql: m073 },
  { version: 75, name: "075-topic-browser-state.sql", sql: m074 },
  { version: 76, name: "076-message-model.sql", sql: m075 },
  { version: 77, name: "077-fix-stale-opus-pricing.sql", sql: m076 },
  { version: 78, name: "078-topic-model-1m-window.sql", sql: m077 },
  { version: 79, name: "079-board-night-mode.sql", sql: m078 },
  { version: 80, name: "080-devices.sql", sql: m079 },
  { version: 81, name: "081-autonomy-default-acts.sql", sql: m080 },
  { version: 82, name: "082-task-shares.sql", sql: m081 },
  { version: 83, name: "083-grants.sql", sql: m082 },
];
