// AUTO-GENERATED by scripts/gen-migrations-manifest.ts — DO NOT EDIT BY HAND.
// Regenerate after adding/renaming a migration:  bun run scripts/gen-migrations-manifest.ts
//
// Embeds every server/db/migrations/*.sql as text so the `bun build --compile`
// server sidecar can run migrations without the on-disk dir (see the script header
// and server/db.ts runMigrations for the disk-vs-embedded fallback).

import m001_initial from "./migrations/001-initial.sql" with { type: "text" };
import m002_agent_autonomy from "./migrations/002-agent-autonomy.sql" with { type: "text" };
import m003_task_archived from "./migrations/003-task-archived.sql" with { type: "text" };
import m004_drop_disabled_templates from "./migrations/004-drop-disabled-templates.sql" with { type: "text" };
import m005_message_branching from "./migrations/005-message-branching.sql" with { type: "text" };
import m006_push_subscriptions from "./migrations/006-push-subscriptions.sql" with { type: "text" };
import m007_ui_state from "./migrations/007-ui-state.sql" with { type: "text" };
import m008_terminal_sessions from "./migrations/008-terminal-sessions.sql" with { type: "text" };
import m009_terminal_claude_session_id from "./migrations/009-terminal-claude-session-id.sql" with { type: "text" };
import m010_topic_provider from "./migrations/010-topic-provider.sql" with { type: "text" };
import m011_terminal_session_status from "./migrations/011-terminal-session-status.sql" with { type: "text" };
import m012_ui_state_payload_version from "./migrations/012-ui-state-payload-version.sql" with { type: "text" };
import m013_topic_model from "./migrations/013-topic-model.sql" with { type: "text" };
import m014_message_meta from "./migrations/014-message-meta.sql" with { type: "text" };
import m015_message_blocks from "./migrations/015-message-blocks.sql" with { type: "text" };
import m016_projects from "./migrations/016-projects.sql" with { type: "text" };
import m017_worktrees from "./migrations/017-worktrees.sql" with { type: "text" };
import m018_topics_worktree_id from "./migrations/018-topics-worktree-id.sql" with { type: "text" };
import m019_topic_initial_message from "./migrations/019-topic-initial-message.sql" with { type: "text" };
import m020_machines from "./migrations/020-machines.sql" with { type: "text" };
import m021_topics_machine_id from "./migrations/021-topics-machine-id.sql" with { type: "text" };
import m022_claude_code_sessions from "./migrations/022-claude-code-sessions.sql" with { type: "text" };
import m023_claude_code_sessions_fk from "./migrations/023-claude-code-sessions-fk.sql" with { type: "text" };
import m024_topic_fast_mode from "./migrations/024-topic-fast-mode.sql" with { type: "text" };
import m025_agent_epochs from "./migrations/025-agent-epochs.sql" with { type: "text" };
import m026_master_topic_mode from "./migrations/026-master-topic-mode.sql" with { type: "text" };
import m027_claude_session_tracker from "./migrations/027-claude-session-tracker.sql" with { type: "text" };
import m028_terminal_parent_session_key from "./migrations/028-terminal-parent-session-key.sql" with { type: "text" };
import m029_terminal_session_type_check from "./migrations/029-terminal-session-type-check.sql" with { type: "text" };
import m030_terminal_session_name_source from "./migrations/030-terminal-session-name-source.sql" with { type: "text" };
import m031_task_dispatch from "./migrations/031-task-dispatch.sql" with { type: "text" };
import m032_terminal_sessions_status_index from "./migrations/032-terminal-sessions-status-index.sql" with { type: "text" };
import m033_topic_effort from "./migrations/033-topic-effort.sql" with { type: "text" };
import m034_task_parent from "./migrations/034-task-parent.sql" with { type: "text" };
import m035_task_output_url from "./migrations/035-task-output-url.sql" with { type: "text" };
import m036_task_plan_first from "./migrations/036-task-plan-first.sql" with { type: "text" };
import m037_task_comment_media from "./migrations/037-task-comment-media.sql" with { type: "text" };
import m038_global_dispatch from "./migrations/038-global-dispatch.sql" with { type: "text" };
import m039_task_comment_kind from "./migrations/039-task-comment-kind.sql" with { type: "text" };
import m040_task_agent_usage from "./migrations/040-task-agent-usage.sql" with { type: "text" };
import m041_task_model from "./migrations/041-task-model.sql" with { type: "text" };
import m042_task_blocked_by from "./migrations/042-task-blocked-by.sql" with { type: "text" };
import m043_task_priority_auto from "./migrations/043-task-priority-auto.sql" with { type: "text" };
import m044_topic_standalone from "./migrations/044-topic-standalone.sql" with { type: "text" };
import m045_backfill_catchall_standalone from "./migrations/045-backfill-catchall-standalone.sql" with { type: "text" };
import m046_standalone_husk_topics from "./migrations/046-standalone-husk-topics.sql" with { type: "text" };
import m047_classify_parked_dispatch_state from "./migrations/047-classify-parked-dispatch-state.sql" with { type: "text" };
import m048_task_agent_cache_read from "./migrations/048-task-agent-cache-read.sql" with { type: "text" };
import m049_topic_mcp_policy from "./migrations/049-topic-mcp-policy.sql" with { type: "text" };
import m050_board_dispatch_retry from "./migrations/050-board-dispatch-retry.sql" with { type: "text" };
import m051_board_dispatch_auto_merge from "./migrations/051-board-dispatch-auto-merge.sql" with { type: "text" };
import m052_board_dispatch_model from "./migrations/052-board-dispatch-model.sql" with { type: "text" };
import m053_board_max_agents_auto from "./migrations/053-board-max-agents-auto.sql" with { type: "text" };
import m054_app_settings from "./migrations/054-app-settings.sql" with { type: "text" };
import m055_task_preview_image from "./migrations/055-task-preview-image.sql" with { type: "text" };
import m056_compaction_markers from "./migrations/056-compaction-markers.sql" with { type: "text" };
import m057_compaction_post_tokens_sanity from "./migrations/057-compaction-post-tokens-sanity.sql" with { type: "text" };
import m058_task_dispatch_defer from "./migrations/058-task-dispatch-defer.sql" with { type: "text" };
import m059_task_delivery_landing from "./migrations/059-task-delivery-landing.sql" with { type: "text" };
import m060_session_context from "./migrations/060-session-context.sql" with { type: "text" };
import m061_review_checks from "./migrations/061-review-checks.sql" with { type: "text" };
import m062_delivered_by from "./migrations/062-delivered-by.sql" with { type: "text" };
import m063_provider_sessions from "./migrations/063-provider-sessions.sql" with { type: "text" };
import m064_topic_goals from "./migrations/064-topic-goals.sql" with { type: "text" };
import m065_task_fanout from "./migrations/065-task-fanout.sql" with { type: "text" };
import m066_terminal_session_type_opencode from "./migrations/066-terminal-session-type-opencode.sql" with { type: "text" };
import m067_drop_master_topic_leftovers from "./migrations/067-drop-master-topic-leftovers.sql" with { type: "text" };
import m068_close_stranded_approvals from "./migrations/068-close-stranded-approvals.sql" with { type: "text" };
import m069_strip_slow_annotation from "./migrations/069-strip-slow-annotation.sql" with { type: "text" };
import m070_message_cache_tokens from "./migrations/070-message-cache-tokens.sql" with { type: "text" };
import m071_drop_empty_assistant_turns from "./migrations/071-drop-empty-assistant-turns.sql" with { type: "text" };
import m072_sweep_dangling_message_refs from "./migrations/072-sweep-dangling-message-refs.sql" with { type: "text" };
import m073_topic_muted from "./migrations/073-topic-muted.sql" with { type: "text" };
import m074_messages_timestamp_index from "./migrations/074-messages-timestamp-index.sql" with { type: "text" };
import m075_topic_browser_state from "./migrations/075-topic-browser-state.sql" with { type: "text" };
import m076_message_model from "./migrations/076-message-model.sql" with { type: "text" };
import m077_fix_stale_opus_pricing from "./migrations/077-fix-stale-opus-pricing.sql" with { type: "text" };
import m078_topic_model_1m_window from "./migrations/078-topic-model-1m-window.sql" with { type: "text" };
import m079_board_night_mode from "./migrations/079-board-night-mode.sql" with { type: "text" };
import m080_devices from "./migrations/080-devices.sql" with { type: "text" };
import m081_autonomy_default_acts from "./migrations/081-autonomy-default-acts.sql" with { type: "text" };
import m082_task_shares from "./migrations/082-task-shares.sql" with { type: "text" };
import m083_grants from "./migrations/083-grants.sql" with { type: "text" };
import m084_people_orgs from "./migrations/084-people-orgs.sql" with { type: "text" };
import m085_share_links from "./migrations/085-share-links.sql" with { type: "text" };
import m086_tool_grants from "./migrations/086-tool-grants.sql" with { type: "text" };
import m087_output_language from "./migrations/087-output-language.sql" with { type: "text" };
import m088_board_language from "./migrations/088-board-language.sql" with { type: "text" };
import m089_retirements from "./migrations/089-retirements.sql" with { type: "text" };
import m090_task_dispatch_weight from "./migrations/090-task-dispatch-weight.sql" with { type: "text" };
import m092_project_org_incognito from "./migrations/092-project-org-incognito.sql" with { type: "text" };
import m093_task_created_by_topic from "./migrations/093-task-created-by-topic.sql" with { type: "text" };
import m094_github_profiles from "./migrations/094-github-profiles.sql" with { type: "text" };
import m095_message_author from "./migrations/095-message-author.sql" with { type: "text" };
import m096_claude_import_offset from "./migrations/096-claude-import-offset.sql" with { type: "text" };
import m097_task_plan_comment from "./migrations/097-task-plan-comment.sql" with { type: "text" };
import m098_task_reopen_trace from "./migrations/098-task-reopen-trace.sql" with { type: "text" };
import m099_landing_witnessed from "./migrations/099-landing-witnessed.sql" with { type: "text" };
import m100_task_labels from "./migrations/100-task-labels.sql" with { type: "text" };
import m101_push_device_prefs from "./migrations/101-push-device-prefs.sql" with { type: "text" };
import m20260812092918_wait_streak_counter from "./migrations/20260812092918-wait-streak-counter.sql" with { type: "text" };
import m20260812093221_discord_presence from "./migrations/20260812093221-discord-presence.sql" with { type: "text" };
import m20260812094300_notification_log from "./migrations/20260812094300-notification-log.sql" with { type: "text" };
import m20260812120000_preview_retired from "./migrations/20260812120000-preview-retired.sql" with { type: "text" };
import m20260813135636_disjoint_cache_creation from "./migrations/20260813135636-disjoint-cache-creation.sql" with { type: "text" };
import m20260814101500_task_interrupt_claim from "./migrations/20260814101500-task-interrupt-claim.sql" with { type: "text" };
import m20260815012042_push_subscription_auth_device from "./migrations/20260815012042-push-subscription-auth-device.sql" with { type: "text" };
import m20260815013610_task_comments_author_kind_index from "./migrations/20260815013610-task-comments-author-kind-index.sql" with { type: "text" };
import m20260815233953_agent_runtime from "./migrations/20260815233953-agent-runtime.sql" with { type: "text" };
import m20260816112635_board_settings_drop_dead_auto_dispatch from "./migrations/20260816112635-board-settings-drop-dead-auto-dispatch.sql" with { type: "text" };
import m20260816142059_board_dispatch_paused from "./migrations/20260816142059-board-dispatch-paused.sql" with { type: "text" };
import m20260816174500_task_delivery_diffstat from "./migrations/20260816174500-task-delivery-diffstat.sql" with { type: "text" };
import m20260816214500_task_review_at from "./migrations/20260816214500-task-review-at.sql" with { type: "text" };
import m20260816230500_grants_project from "./migrations/20260816230500-grants-project.sql" with { type: "text" };
import m20260817165727_profile_publish_cost from "./migrations/20260817165727-profile-publish-cost.sql" with { type: "text" };
import m20260818052603_profile_share_token from "./migrations/20260818052603-profile-share-token.sql" with { type: "text" };
import m20260818110000_machine_notes_are_service from "./migrations/20260818110000-machine-notes-are-service.sql" with { type: "text" };
import m20260818120000_timeout_is_not_a_red from "./migrations/20260818120000-timeout-is-not-a-red.sql" with { type: "text" };

export interface EmbeddedMigration {
  version: number;
  name: string;
  sql: string;
}

/** All migrations in ascending version order, embedded at build time. */
export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [
  { version: 1, name: "001-initial.sql", sql: m001_initial },
  { version: 2, name: "002-agent-autonomy.sql", sql: m002_agent_autonomy },
  { version: 3, name: "003-task-archived.sql", sql: m003_task_archived },
  { version: 4, name: "004-drop-disabled-templates.sql", sql: m004_drop_disabled_templates },
  { version: 5, name: "005-message-branching.sql", sql: m005_message_branching },
  { version: 6, name: "006-push-subscriptions.sql", sql: m006_push_subscriptions },
  { version: 7, name: "007-ui-state.sql", sql: m007_ui_state },
  { version: 8, name: "008-terminal-sessions.sql", sql: m008_terminal_sessions },
  { version: 9, name: "009-terminal-claude-session-id.sql", sql: m009_terminal_claude_session_id },
  { version: 10, name: "010-topic-provider.sql", sql: m010_topic_provider },
  { version: 11, name: "011-terminal-session-status.sql", sql: m011_terminal_session_status },
  { version: 12, name: "012-ui-state-payload-version.sql", sql: m012_ui_state_payload_version },
  { version: 13, name: "013-topic-model.sql", sql: m013_topic_model },
  { version: 14, name: "014-message-meta.sql", sql: m014_message_meta },
  { version: 15, name: "015-message-blocks.sql", sql: m015_message_blocks },
  { version: 16, name: "016-projects.sql", sql: m016_projects },
  { version: 17, name: "017-worktrees.sql", sql: m017_worktrees },
  { version: 18, name: "018-topics-worktree-id.sql", sql: m018_topics_worktree_id },
  { version: 19, name: "019-topic-initial-message.sql", sql: m019_topic_initial_message },
  { version: 20, name: "020-machines.sql", sql: m020_machines },
  { version: 21, name: "021-topics-machine-id.sql", sql: m021_topics_machine_id },
  { version: 22, name: "022-claude-code-sessions.sql", sql: m022_claude_code_sessions },
  { version: 23, name: "023-claude-code-sessions-fk.sql", sql: m023_claude_code_sessions_fk },
  { version: 24, name: "024-topic-fast-mode.sql", sql: m024_topic_fast_mode },
  { version: 25, name: "025-agent-epochs.sql", sql: m025_agent_epochs },
  { version: 26, name: "026-master-topic-mode.sql", sql: m026_master_topic_mode },
  { version: 27, name: "027-claude-session-tracker.sql", sql: m027_claude_session_tracker },
  { version: 28, name: "028-terminal-parent-session-key.sql", sql: m028_terminal_parent_session_key },
  { version: 29, name: "029-terminal-session-type-check.sql", sql: m029_terminal_session_type_check },
  { version: 30, name: "030-terminal-session-name-source.sql", sql: m030_terminal_session_name_source },
  { version: 31, name: "031-task-dispatch.sql", sql: m031_task_dispatch },
  { version: 32, name: "032-terminal-sessions-status-index.sql", sql: m032_terminal_sessions_status_index },
  { version: 33, name: "033-topic-effort.sql", sql: m033_topic_effort },
  { version: 34, name: "034-task-parent.sql", sql: m034_task_parent },
  { version: 35, name: "035-task-output-url.sql", sql: m035_task_output_url },
  { version: 36, name: "036-task-plan-first.sql", sql: m036_task_plan_first },
  { version: 37, name: "037-task-comment-media.sql", sql: m037_task_comment_media },
  { version: 38, name: "038-global-dispatch.sql", sql: m038_global_dispatch },
  { version: 39, name: "039-task-comment-kind.sql", sql: m039_task_comment_kind },
  { version: 40, name: "040-task-agent-usage.sql", sql: m040_task_agent_usage },
  { version: 41, name: "041-task-model.sql", sql: m041_task_model },
  { version: 42, name: "042-task-blocked-by.sql", sql: m042_task_blocked_by },
  { version: 43, name: "043-task-priority-auto.sql", sql: m043_task_priority_auto },
  { version: 44, name: "044-topic-standalone.sql", sql: m044_topic_standalone },
  { version: 45, name: "045-backfill-catchall-standalone.sql", sql: m045_backfill_catchall_standalone },
  { version: 46, name: "046-standalone-husk-topics.sql", sql: m046_standalone_husk_topics },
  { version: 47, name: "047-classify-parked-dispatch-state.sql", sql: m047_classify_parked_dispatch_state },
  { version: 48, name: "048-task-agent-cache-read.sql", sql: m048_task_agent_cache_read },
  { version: 49, name: "049-topic-mcp-policy.sql", sql: m049_topic_mcp_policy },
  { version: 50, name: "050-board-dispatch-retry.sql", sql: m050_board_dispatch_retry },
  { version: 51, name: "051-board-dispatch-auto-merge.sql", sql: m051_board_dispatch_auto_merge },
  { version: 52, name: "052-board-dispatch-model.sql", sql: m052_board_dispatch_model },
  { version: 53, name: "053-board-max-agents-auto.sql", sql: m053_board_max_agents_auto },
  { version: 54, name: "054-app-settings.sql", sql: m054_app_settings },
  { version: 55, name: "055-task-preview-image.sql", sql: m055_task_preview_image },
  { version: 56, name: "056-compaction-markers.sql", sql: m056_compaction_markers },
  { version: 57, name: "057-compaction-post-tokens-sanity.sql", sql: m057_compaction_post_tokens_sanity },
  { version: 58, name: "058-task-dispatch-defer.sql", sql: m058_task_dispatch_defer },
  { version: 59, name: "059-task-delivery-landing.sql", sql: m059_task_delivery_landing },
  { version: 60, name: "060-session-context.sql", sql: m060_session_context },
  { version: 61, name: "061-review-checks.sql", sql: m061_review_checks },
  { version: 62, name: "062-delivered-by.sql", sql: m062_delivered_by },
  { version: 63, name: "063-provider-sessions.sql", sql: m063_provider_sessions },
  { version: 64, name: "064-topic-goals.sql", sql: m064_topic_goals },
  { version: 65, name: "065-task-fanout.sql", sql: m065_task_fanout },
  { version: 66, name: "066-terminal-session-type-opencode.sql", sql: m066_terminal_session_type_opencode },
  { version: 67, name: "067-drop-master-topic-leftovers.sql", sql: m067_drop_master_topic_leftovers },
  { version: 68, name: "068-close-stranded-approvals.sql", sql: m068_close_stranded_approvals },
  { version: 69, name: "069-strip-slow-annotation.sql", sql: m069_strip_slow_annotation },
  { version: 70, name: "070-message-cache-tokens.sql", sql: m070_message_cache_tokens },
  { version: 71, name: "071-drop-empty-assistant-turns.sql", sql: m071_drop_empty_assistant_turns },
  { version: 72, name: "072-sweep-dangling-message-refs.sql", sql: m072_sweep_dangling_message_refs },
  { version: 73, name: "073-topic-muted.sql", sql: m073_topic_muted },
  { version: 74, name: "074-messages-timestamp-index.sql", sql: m074_messages_timestamp_index },
  { version: 75, name: "075-topic-browser-state.sql", sql: m075_topic_browser_state },
  { version: 76, name: "076-message-model.sql", sql: m076_message_model },
  { version: 77, name: "077-fix-stale-opus-pricing.sql", sql: m077_fix_stale_opus_pricing },
  { version: 78, name: "078-topic-model-1m-window.sql", sql: m078_topic_model_1m_window },
  { version: 79, name: "079-board-night-mode.sql", sql: m079_board_night_mode },
  { version: 80, name: "080-devices.sql", sql: m080_devices },
  { version: 81, name: "081-autonomy-default-acts.sql", sql: m081_autonomy_default_acts },
  { version: 82, name: "082-task-shares.sql", sql: m082_task_shares },
  { version: 83, name: "083-grants.sql", sql: m083_grants },
  { version: 84, name: "084-people-orgs.sql", sql: m084_people_orgs },
  { version: 85, name: "085-share-links.sql", sql: m085_share_links },
  { version: 86, name: "086-tool-grants.sql", sql: m086_tool_grants },
  { version: 87, name: "087-output-language.sql", sql: m087_output_language },
  { version: 88, name: "088-board-language.sql", sql: m088_board_language },
  { version: 89, name: "089-retirements.sql", sql: m089_retirements },
  { version: 90, name: "090-task-dispatch-weight.sql", sql: m090_task_dispatch_weight },
  { version: 92, name: "092-project-org-incognito.sql", sql: m092_project_org_incognito },
  { version: 93, name: "093-task-created-by-topic.sql", sql: m093_task_created_by_topic },
  { version: 94, name: "094-github-profiles.sql", sql: m094_github_profiles },
  { version: 95, name: "095-message-author.sql", sql: m095_message_author },
  { version: 96, name: "096-claude-import-offset.sql", sql: m096_claude_import_offset },
  { version: 97, name: "097-task-plan-comment.sql", sql: m097_task_plan_comment },
  { version: 98, name: "098-task-reopen-trace.sql", sql: m098_task_reopen_trace },
  { version: 99, name: "099-landing-witnessed.sql", sql: m099_landing_witnessed },
  { version: 100, name: "100-task-labels.sql", sql: m100_task_labels },
  { version: 101, name: "101-push-device-prefs.sql", sql: m101_push_device_prefs },
  { version: 20260812092918, name: "20260812092918-wait-streak-counter.sql", sql: m20260812092918_wait_streak_counter },
  { version: 20260812093221, name: "20260812093221-discord-presence.sql", sql: m20260812093221_discord_presence },
  { version: 20260812094300, name: "20260812094300-notification-log.sql", sql: m20260812094300_notification_log },
  { version: 20260812120000, name: "20260812120000-preview-retired.sql", sql: m20260812120000_preview_retired },
  { version: 20260813135636, name: "20260813135636-disjoint-cache-creation.sql", sql: m20260813135636_disjoint_cache_creation },
  { version: 20260814101500, name: "20260814101500-task-interrupt-claim.sql", sql: m20260814101500_task_interrupt_claim },
  { version: 20260815012042, name: "20260815012042-push-subscription-auth-device.sql", sql: m20260815012042_push_subscription_auth_device },
  { version: 20260815013610, name: "20260815013610-task-comments-author-kind-index.sql", sql: m20260815013610_task_comments_author_kind_index },
  { version: 20260815233953, name: "20260815233953-agent-runtime.sql", sql: m20260815233953_agent_runtime },
  { version: 20260816112635, name: "20260816112635-board-settings-drop-dead-auto-dispatch.sql", sql: m20260816112635_board_settings_drop_dead_auto_dispatch },
  { version: 20260816142059, name: "20260816142059-board-dispatch-paused.sql", sql: m20260816142059_board_dispatch_paused },
  { version: 20260816174500, name: "20260816174500-task-delivery-diffstat.sql", sql: m20260816174500_task_delivery_diffstat },
  { version: 20260816214500, name: "20260816214500-task-review-at.sql", sql: m20260816214500_task_review_at },
  { version: 20260816230500, name: "20260816230500-grants-project.sql", sql: m20260816230500_grants_project },
  { version: 20260817165727, name: "20260817165727-profile-publish-cost.sql", sql: m20260817165727_profile_publish_cost },
  { version: 20260818052603, name: "20260818052603-profile-share-token.sql", sql: m20260818052603_profile_share_token },
  { version: 20260818110000, name: "20260818110000-machine-notes-are-service.sql", sql: m20260818110000_machine_notes_are_service },
  { version: 20260818120000, name: "20260818120000-timeout-is-not-a-red.sql", sql: m20260818120000_timeout_is_not_a_red },
];
