/**
 * @covers SCHEMA-01
 */
// DRIFT GATE for the embedded-migrations manifest.
//
// The server sidecar (bun build --compile) can't read server/db/migrations/*.sql
// from disk — import.meta.dir is virtual there — so it runs the migrations baked
// into migrations-embedded.ts (generated by scripts/gen-migrations-manifest.ts).
// If someone adds/renames/edits a migration and forgets to regenerate, the app
// ships with a SILENTLY out-of-date schema. This test makes that impossible: it
// fails unless the manifest matches the on-disk migrations 1:1 (version + name +
// exact SQL). Fix a failure with:  bun run scripts/gen-migrations-manifest.ts

import { test, expect } from "bun:test";
import { readdirSync, readFileSync } from "fs";
import { join } from "path";
import { EMBEDDED_MIGRATIONS } from "./migrations-embedded";

const MIGRATIONS_DIR = join(import.meta.dir, "migrations");

/** The on-disk migrations, in the same shape + order as the manifest. */
function diskMigrations() {
  return readdirSync(MIGRATIONS_DIR)
    .filter((f) => /^\d+-.+\.sql$/.test(f))
    .sort()
    .map((name) => ({
      version: parseInt(name.match(/^(\d+)-/)![1], 10),
      name,
      sql: readFileSync(join(MIGRATIONS_DIR, name), "utf-8"),
    }));
}

test("embedded manifest covers every on-disk migration (regenerate if this fails)", () => {
  const disk = diskMigrations();
  const embeddedNames = EMBEDDED_MIGRATIONS.map((m) => m.name).sort();
  const diskNames = disk.map((m) => m.name).sort();
  // Surface a readable filename diff before the deeper content assertion.
  expect(embeddedNames).toEqual(diskNames);
});

test("embedded manifest matches disk 1:1 on version + name + SQL content", () => {
  const disk = diskMigrations();
  const embedded = EMBEDDED_MIGRATIONS.slice().sort((a, b) => a.version - b.version);

  expect(embedded.length).toBe(disk.length);
  for (const d of disk) {
    const e = embedded.find((m) => m.name === d.name);
    expect(e, `migration ${d.name} missing from embedded manifest`).toBeDefined();
    expect(e!.version, `version mismatch for ${d.name}`).toBe(d.version);
    // Exact byte-for-byte SQL — catches an EDITED migration whose manifest text
    // is stale, not just added/removed files.
    expect(e!.sql, `SQL content drift for ${d.name} — regenerate the manifest`).toBe(d.sql);
  }
});

// L'ORDINE dell'array non è un'asserzione, e non è una dimenticanza.
// `resolveMigrations` (server/db.ts) riordina sempre per (numero, nome) prima di
// applicare, e il manifest è marcato `merge=union` in .gitattributes apposta
// perché due card in parallelo possano aggiungere una riga ciascuna senza
// conflitto: subito dopo quel merge le ultime due righe possono stare in
// qualsiasi ordine. Preteserlo crescente qui renderebbe rosso proprio il caso
// che si è voluto rendere possibile.
//
// Il NOME invece è l'identità (il registro `schema_migrations` è indicizzato
// così): due entry con lo stesso nome sarebbero una migration applicata due
// volte, ed è quello che si controlla.
test("ogni migration compare UNA volta nel manifest, e il numero è quello del nome", () => {
  const names = EMBEDDED_MIGRATIONS.map((m) => m.name);
  expect(new Set(names).size).toBe(names.length);
  for (const m of EMBEDDED_MIGRATIONS) {
    expect(m.version, `numero incoerente col nome per ${m.name}`)
      .toBe(parseInt(m.name.match(/^(\d+)-/)![1], 10));
  }
});
