/**
 * Il DEBITO: i file tracciati che portano ancora il nome di chi lavora al repo.
 *
 * Non e' un'allowlist, e' un conto aperto. Vive in un file suo perche' il
 * cancello (`no-personal-data-tracked.test.ts`) fa due cose diverse con questa
 * lista, e tenerle separate e' cio' che la fa RIDURRE invece di crescere:
 *
 *   • un file che porta un termine e NON e' qui dentro fa fallire il cancello,
 *     quindi l'elenco non puo' allungarsi di nascosto;
 *   • una voce qui dentro che NON porta piu' un termine fa fallire il cancello,
 *     quindi l'elenco non puo' restare gonfio dopo una pulizia.
 *
 * PERCHE' NON SI CHIUDE A MANO. Questi file sono anche dentro gli SHA dei
 * commit non ancora spinti: ripulirli qui non li toglierebbe dal pubblico,
 * perche' `git log -p` continuerebbe a mostrarli. Si chiudono tutti insieme
 * quando la storia viene riscritta (git-filter-repo, `--replace-text`), che e'
 * l'unico passaggio che tocca sia l'albero sia la storia. Fino ad allora questo
 * elenco e' la misura esatta di quanto manca.
 *
 * Generato una volta e poi POTATO a mano: non c'e' uno script che lo rigeneri,
 * di proposito. Rigenerarlo lo farebbe ricrescere in silenzio.
 */
export const DEBITO_NOME_PROPRIETARIO: readonly string[] = [
  "CHANGELOG.md",
  "PORTING-PLAN.md",
  "client/public/changelog.json",
  "client/src/App.tsx",
  "client/src/components/Board/Card.tsx",
  "client/src/components/Board/KanbanBoardPane.tsx",
  "client/src/components/Board/PreviewMedia.tsx",
  "client/src/components/Board/TaskDetail.tsx",
  "client/src/components/Board/atoms.tsx",
  "client/src/components/Board/constants.ts",
  "client/src/components/Board/dndSensors.ts",
  "client/src/components/Board/taskMedia.test.ts",
  "client/src/components/Layout/GroupLayout.tsx",
  "client/src/components/Layout/PaneTabBar.tsx",
  "client/src/components/Layout/ProjectWindow.tsx",
  "client/src/components/Layout/StreamingIndicator.tsx",
  "client/src/components/Project/ProjectSidebar.tsx",
  "client/src/components/Project/projectSidebarHeights.ts",
  "client/src/components/Settings/accountState.test.ts",
  "client/src/components/Shared/PaneAddMenu.tsx",
  "client/src/components/Shared/ProjectFavicon.tsx",
  "client/src/components/Shared/SidebarUpdateBanner.tsx",
  "client/src/components/Sidebar/BoardStatusCounts.tsx",
  "client/src/components/Sidebar/MobileChromeBar.tsx",
  "client/src/components/Sidebar/PinnedTile.tsx",
  "client/src/components/Sidebar/PinnedTiles.tsx",
  "client/src/components/Sidebar/SidebarStatusBar.tsx",
  "client/src/components/Sidebar/SidebarSystemMenu.tsx",
  "client/src/components/Sidebar/TopicTree.tsx",
  "client/src/components/Sidebar/boardProjectChips.test.ts",
  "client/src/components/Sidebar/boardProjectChips.ts",
  "client/src/components/Sidebar/pinnedTileMetrics.ts",
  "client/src/components/Sidebar/useCellFlip.ts",
  "client/src/components/Terminal/SingleTerminalPane.tsx",
  "client/src/hooks/useSidebarAndLayout.ts",
  "client/src/hooks/useSidebarState.ts",
  "client/src/hooks/useSidebarSwipe.ts",
  "client/src/hooks/useTauriBrowser.ts",
  "client/src/hooks/useTouchDrag.ts",
  "client/src/index.css",
  "client/src/lib/auth/session.ts",
  "client/src/lib/board.ts",
  "client/src/lib/browserKeyboardProfile.ts",
  "client/src/lib/edgeSwipeGuard.ts",
  "client/src/lib/haptics.ts",
  "client/src/lib/selectionStyles.test.ts",
  "client/src/lib/selectionStyles.ts",
  "client/src/state/pane/selectors.test.ts",
  "client/src/state/pane/selectors.ts",
  "desktop-tauri/src-tauri/src/lib.rs",
  "docs/board-protocol.md",
  "openspec/changes/archive/2026-07-30-remove-dead-fuzzy-signal/proposal.md",
  "openspec/changes/autonomous-credential-store/design.md",
  "openspec/changes/autonomous-credential-store/proposal.md",
  "openspec/changes/autonomous-credential-store/specs/app-signing/spec.md",
  "openspec/changes/autonomous-credential-store/tasks.md",
  "openspec/changes/human-reopen-out-of-review/proposal.md",
  "openspec/changes/kanban-agent-authoring/proposal.md",
  "openspec/changes/lan-open-same-origin/design.md",
  "openspec/changes/lan-open-same-origin/tasks.md",
  "openspec/changes/relay/tasks.md",
  "openspec/changes/remappable-shortcuts/proposal.md",
  "openspec/changes/sidebar-pinned-tiles/proposal.md",
  "openspec/changes/sidebar-pinned-tiles/tasks.md",
  "scripts/browser-orphan-bar.sh",
  "scripts/check-emdash.ts",
  "scripts/mcp-cap-bench/bench.ts",
  "server.ts",
  "server/browser-chromium-sidecar.ts",
  "server/db/migrations/080-devices.sql",
  "server/db/migrations/089-retirements.sql",
  "server/db/migrations/100-task-labels.sql",
  "server/lib/account.test.ts",
  "server/lib/auth-gate.test.ts",
  "server/lib/browser-orphan-sweep.test.ts",
  "server/lib/browser-orphan-sweep.ts",
  "server/lib/device-auth.test.ts",
  "server/lib/project-visibility.test.ts",
  "server/mcp/topics-mcp-server.test.ts",
  "server/providers/claude-models.ts",
  "server/routes/account.test.ts",
  "server/routes/tasks.test.ts",
  "server/routes/tasks.ts",
  "server/services/preview-manager.ts",
  "server/services/retirement.ts",
  "server/services/task-dispatcher.test.ts",
  "server/services/task-merge.test.ts",
  "server/services/task-model-picker.ts",
  "server/services/tasks.parked-stall.test.ts",
  "server/services/tasks.queue-reason.test.ts",
  "server/services/tasks.test.ts",
  "server/services/tasks.ts",
  "shared/board.ts",
  "shared/task-labels.ts",
  "spike/rrweb-cobrowse/EVALUATION.md",
  "spike/rrweb-cobrowse/README.md",
  "tests/e2e/board-drawer-truth.spec.ts",
  "tests/e2e/board-labels.spec.ts",
  "tests/e2e/board-preview-cap.spec.ts",
  "tests/e2e/board-reopened-chip.spec.ts",
  "tests/e2e/board-task-id-chip.spec.ts",
  "tests/e2e/checklist-ui-verify.spec.ts",
  "tests/e2e/chrome-bar-continuity.spec.ts",
  "tests/e2e/chrome-bar-overlay.spec.ts",
  "tests/e2e/external-session-adopt.spec.ts",
  "tests/e2e/file-explorer-cache.spec.ts",
  "tests/e2e/mobile-chrome-bar.spec.ts",
  "tests/e2e/pane-over-pane-group.spec.ts",
  "tests/e2e/panels.spec.ts",
  "tests/e2e/project-rail-row-gap.spec.ts",
  "tests/e2e/project-sidebar-auto-height.spec.ts",
  "tests/e2e/project-sidebar-rail.spec.ts",
  "tests/e2e/project-sidebar-sections-resize.spec.ts",
  "tests/e2e/project-tabs.spec.ts",
  "tests/e2e/refresh-cls.spec.ts",
  "tests/e2e/row-actions-overlay.spec.ts",
  "tests/e2e/sidebar-content-seam.spec.ts",
  "tests/e2e/sidebar-finger-follow.spec.ts",
  "tests/e2e/sidebar-header-gap.spec.ts",
  "tests/e2e/sidebar-pinned-tiles.spec.ts",
  "tests/e2e/sidebar-touch-audit.spec.ts",
  "tests/e2e/sidebar.spec.ts",
  "tests/e2e/sub-chrome-row.spec.ts",
  "tests/e2e/tab-bar-command-air.spec.ts",
  "tests/e2e/tab-coherence-mobile.spec.ts",
  "tests/e2e/tab-widget-geometry.spec.ts",
  "tests/integration/auth-routes.test.ts",
  "tests/integration/migration-092-project-org-incognito.test.ts",
  "tests/integration/migration-095-message-author.test.ts",
  "tests/integration/migration-098-task-reopen-trace.test.ts",
  "tests/unit/ws-outbound-coverage.test.ts",
];
