// @generated by scripts/gen-shortcuts.ts from shared/shortcuts.ts. DO NOT EDIT.
// Run `bun run gen:shortcuts` after changing the keyboard-shortcut registry;
// `shared/shortcuts.test.ts` fails in CI if this file drifts from the registry.

/// Is `chars` (charactersIgnoringModifiers, lowercase) a forwarded ⌘-chord?
/// The caller has already checked `cmd && !ctrl`. Mirrors the `native` entries
/// of the shortcut registry; the re-dispatched `key` is `chars` itself.
#[cfg(target_os = "macos")]
pub fn is_forwarded_cmd_chord(shift: bool, chars: &str) -> bool {
    match chars {
        "?" | "/" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "b" | "k" | "n" | "p" | "t" | "w" => true,
        "u" => shift,
        _ => false,
    }
}
