name: notifications-redesign
status: approved
creato: 2026-10-03
richiesta: "inoltre ti segnalo che mi da portando le notifiche sulle pane, anche se in realtà è in attesa di lavori in bg, dovremmmo volutare al meglio tutto il sistema di notifiche e rifarlo al meglio perchè al momento non sono sincronizzare e reali neanche le notifiche dal tasto sidebar"
approvato: 2026-10-03 23:22
risposta: "mi sembra top! vai pure"
